= Compute options for Microservices on AWS

Amazon Web Services offers a wide range of compute options for developers interested in deploying microservices-based applications. Developers interested in full control and responsibility of the stack can use EC2 and deploy all components from scratch. If you are interested in leveraging containers then you can deploy your applications using Amazon EC2 Container Service or a Kubernetes cluster on AWS. Serverless applications can be deployed using AWS Lambda. The amount of effort, time and resources involved to address Ops concerns such as creating, managing, scaling and updating a cluster differ for each compute option. Similarly, Developer concerns such as application packaging, tooling, service discovery, monitoring, logging, and CI/CD also differ for each compute option. This session will walk you through what it takes to build, deploy and manage a simple microservices based application using these different compute options. You'll learn when a particular option is well suited, or not for your application. Pros and cons of each option will be discussed as well. Attendees will take home a working code sample for each compute option.