= Service Discovery in Container Orchestration Frameworks

Service registration, discovery and horizontal scalability are key operational requirements of a microservice architecture.Each service needs to replicate. A standard mechanism by which services can easily scale up and down based upon metadata is important. The exact address of a service may not be known until the service is deployed and ready to be used. The dynamic nature of a service’s endpoint address is handled by service registration, discovery and a load balancer. This is all the more important in a containerized world where each container is like a cattle.Docker, Kubernetes, DC/OS and ECS are commonly used container orchestration platforms. They all have built-in support for service discovery and scalability. This talk will explain how this requirement of microservices are met in these orchestration frameworks. Specifically, configuration files for three microservices talking to each other will be shown and explained for the different frameworks.