= Amazon Corretto

Amazon Corretto is a no-cost, multiplatform, production-ready distribution of the OpenJDK. Corretto comes with long-term support that will include performance enhancements and security fixes. Amazon runs Corretto internally on thousands of production services and Corretto is certified as compatible with the Java SE standard. With Corretto, you can develop and run Java applications on popular operating systems, including Amazon Linux 2, Windows, and macOS. This talk will explain on why Amazon Corretto was created. Upstream compatibility to OpenJDK is a core tenet of Corretto. Attendees will learn how an upstream OpenJDK build is published as Corretto. You'll learn how to get started with Corretto and collaborate in open source.

== Building Java in the Open

OpenJDK is the open source implementation of the Java platform. Amazon Corretto is a no-cost, multiplatform, production-ready distribution of the OpenJDK. Upstream compatibility to OpenJDK is a core tenet of Corretto. Amazon runs Corretto internally on thousands of production services and Corretto is certified as compatible with the Java SE standard. This talk will explain on why Amazon Corretto was created. It will explain the journey of how a downstream distribution of Corretto is created from OpenJDK and how a contribution is upstreamed to OpenJDK. Attendees will learn how Java is truly built in the open. We will also share stories about cultural changes to collaborate in the open source.