= Using Kubernetes for Machine Learning Frameworks

Kubernetes provides isolation, auto-scaling, load balancing, flexibility and GPU support. These features are critical to run computationally, data intensive and hard to parallelize machine learning models. Declarative syntax of Kubernetes deployment descriptors make it easy for non-operationally focused engineers to easily train machine learning models on Kubernetes. This talk will explain why and how Kubernetes is well suited for single and multi node distributed training, deploying your machine learning models in production and setting up visualization tools like TensorBoard for monitoring. Specifically it will show how to setup a variety of open source machine learning frameworks such as TensorFlow, Apache MXNet and Pytorch on a Kubernetes cluster. The attendees will learn distributed training, massaging and inference phases of setting up a Machine Learning framework on Kubernetes. Attendees will leave with a GitHub repo of fully working samples.

- Attendees will learn why Kubernetes is well suited to run machine learning frameworks
- They will see how the most popular open source ML frameworks can run on Kubernetes
- They will leave with a working sample using GitHub repos

== Alternative abstract

Kubernetes provides isolation, auto-scaling, load balancing, flexibility and GPU support. These features are critical to run computationally, data intensive and hard to parallelize machine learning models. Declarative syntax of Kubernetes deployment descriptors make it easy for non-operationally focused engineers to easily train machine learning models on Kubernetes. This talk will explain why and how Kubernetes is well suited for single- and multi-node distributed training, training your models, and deploying your models in production. Specifically it will show how to use KubeFlow and TensorFlow for your machine learning needs. We will also show to setup machine learning pipelines and set up visualization tools like TensorBoard for monitoring. We will also discuss distributed training using Horovod.

== Alternative abstract

Machine Learning on Amazon EKS

Kubernetes provides isolation, auto-scaling, load balancing, flexibility and GPU support. These features are critical to run computationally, data intensive and hard to parallelize machine learning models. Declarative syntax of Kubernetes deployment descriptors make it easy for non-operationally focused engineers to easily train machine learning models on Kubernetes. This talk will explain why and how Amazon EKS is well suited for single- and multi-node distributed training, training your models, and deploying your models in production. Specifically it will show how to use KubeFlow and TensorFlow on Amazon EKS for your machine learning needs. We will also show to setup machine learning pipelines and set up visualization tools like TensorBoard for monitoring. We will also discuss distributed training using Horovod.

== Alternative abstract

Machine Learning using Kubeflow and Kubernetes

The Kubeflow project makes deployments of machine learning (ML) workflows on Kubernetes simple, portable and scalable. Kubeflow comes with Jupyter notebook, training and inference using Tensorflow, hyperparameter tuning using Katib, end-to-end automated deployment pipelines using Argo, hyperparameter tuning using Katib, and much more. This talk will explain why and how Kubernetes is well suited for single- and multi-node distributed training, training your models, and deploying your models for inference in production. Specifically it will show how to use KubeFlow and TensorFlow for your machine learning needs. We will also show to setup machine learning pipelines and set up visualization tools like TensorBoard for monitoring. We will also discuss distributed training using Horovod.


== Outline

- why k8s for machine learning
- key components of ML (training, cleaning up data, inference)
- intro to kubeflow
- TensorFlow using kubeflow
- Pytorch using kubeflow
- MXNet on k8s


